import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant":              "#33343b",
        "surface-container-lowest":     "#0c0e14",
        "surface-container":            "#1e1f26",
        "surface-container-high":       "#282a30",
        "surface-container-highest":    "#33343b",
        "surface-container-low":        "#191b22",
        "surface-dim":                  "#111319",
        "surface-bright":               "#373940",
        "surface":                      "#111319",
        "background":                   "#111319",
        "on-background":                "#e2e2eb",
        "on-surface":                   "#e2e2eb",
        "on-surface-variant":           "#bcc9cd",
        "inverse-surface":              "#e2e2eb",
        "inverse-on-surface":           "#2e3037",
        "outline":                      "#869397",
        "outline-variant":              "#3d494c",
        "primary":                      "#4cd7f6",
        "on-primary":                   "#003640",
        "primary-container":            "#06b6d4",
        "on-primary-container":         "#00424f",
        "primary-fixed":                "#acedff",
        "primary-fixed-dim":            "#4cd7f6",
        "on-primary-fixed":             "#001f26",
        "on-primary-fixed-variant":     "#004e5c",
        "inverse-primary":              "#00687a",
        "surface-tint":                 "#4cd7f6",
        "secondary":                    "#d0bcff",
        "on-secondary":                 "#3c0091",
        "secondary-container":          "#571bc1",
        "on-secondary-container":       "#c4abff",
        "secondary-fixed":              "#e9ddff",
        "secondary-fixed-dim":          "#d0bcff",
        "on-secondary-fixed":           "#23005c",
        "on-secondary-fixed-variant":   "#5516be",
        "tertiary":                     "#ffb95f",
        "on-tertiary":                  "#472a00",
        "tertiary-container":           "#e79400",
        "on-tertiary-container":        "#563400",
        "tertiary-fixed":               "#ffddb8",
        "tertiary-fixed-dim":           "#ffb95f",
        "on-tertiary-fixed":            "#2a1700",
        "on-tertiary-fixed-variant":    "#653e00",
        "error":                        "#ffb4ab",
        "on-error":                     "#690005",
        "error-container":              "#93000a",
        "on-error-container":           "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm:      "0.125rem",
        md:      "0.375rem",
        lg:      "0.25rem",
        xl:      "0.5rem",
        "2xl":   "1rem",
        full:    "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
